title: Lambert Kofi Gyan Danquah 
params:
  theme:
    highlightJS: true
    highlightTheme: "monokai"
    logo: "/images/logo.png"  # Replace with your logo
    showDate: true
    showTags: true
    paginate: 10
    postSummary: true
    socials:
            github: "https://github.com/LambertDanquah"
