# Theme Settings
minimal_mistakes_skin: "default" # Theme skin options: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-GB"
title: "Lambert Kofi Gyan Danquah"
title_separator: "-"
name: "Lambert Kofi Gyan Danquah"
description: >
  Machine learning researcher with interests in AI, privacy-preserving methods, IoT security, and federated learning. Expertise in building computationally efficient models for botnet attack detection.
url: "https://yourdomain.com" # Change to your domain
baseurl: "/" # The subpath of your site
repository: "yourgithubusername/yourrepository" # GitHub username/repo-name
teaser: "/assets/images/lambert-avatar.jpg" # Path of fallback teaser image
words_per_minute: 200

# Comments
comments:
  provider: false # Disable comments

# Search Settings
search: true
search_full_content: false
search_provider: lunr

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-XXXXXXXXX-X"
    anonymize_ip: false

# Author Information
author:
  name: "Lambert Kofi Gyan Danquah"
  avatar: "/assets/images/lambert-avatar.jpg"
  bio: "Machine Learning and AI Researcher. MSc in Computer Engineering from KNUST."
  location: "Ghana"
  email: "lambert@example.com"
  github: "lambert-github"
  twitter: "lambert-twitter"
  linkedin: "lambert-linkedin"

# Social Sharing
social:
  type: "Person"
  name: "Lambert Kofi Gyan Danquah"
  links:
    - "https://github.com/lambert-github"
    - "https://twitter.com/lambert-twitter"
    - "https://linkedin.com/in/lambert-linkedin"

# Site Content
include:
  - .htaccess
  - _pages
  - _posts
exclude:
  - node_modules
  - vendor

# Markdown and Output Settings
markdown: kramdown
highlighter: rouge

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults for Posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Defaults for Pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
